
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orders-sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte123!
    ports:
      - "14333:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    hostname: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

volumes:
  sqlserver_data: